name: Publish

on:
  push:
    tags: ["v*.*.*"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # # This is used to complete the identity challenge
      # # with sigstore/fulcio when running outside of PRs.
      # id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: charts/k8s-prowler
          repository: devopzilla
          tag: ${{ steps.vars.outputs.tag }}
          path: chart
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
